Add Embed Interface Structure
LibraryofCode/discordts pull request #24
Opened 2021-04-20 20:48 UTC by matthew119427

This PR adds an `index.ts` file as well as the `Embed` interface structure.

2021-04-20 21:35 UTC, bsian03 commented
You seemed to have made the commit from your beta branch on your fork instead of the base repository, can you reset and cherry-pick the user interface commit? Same for #25

2021-04-21 07:41 UTC, Khaaz commented
lgtm, just waiting for the cherry pick (conflict / extend) with the Base

2021-04-22 14:54 UTC, bsian03 requested changes
Can the interfaces be in alphabetical order as well?

2021-04-22 14:54 UTC, bsian03 commented on structures/Base.ts
> +}
Won't need this for now

2021-04-22 14:54 UTC, bsian03 commented on structures/Embed.ts
> +export interface EmbedFooter {
Missing proxy url

2021-04-22 14:54 UTC, bsian03 commented on structures/Embed.ts
> +  type?: 'rich' | 'image' | 'video' | 'gifv' | 'article' | 'link';
Can this be type aliased

2021-04-22 15:29 UTC, SiroTM commented
EmbedFooter is defined twice

2021-04-23 10:16 UTC, Khaaz commented on structures/Embed.ts
> +  type?: 'rich' | 'image' | 'video' | 'gifv' | 'article' | 'link';
an enum for this would be good yes

2021-06-12 03:55 UTC, matthew119427 commented
See #42

2021-06-12 03:55 UTC, closed without merging