feat(structures): Role interface
LibraryofCode/discordts pull request #33
Opened 2021-06-07 23:33 UTC by SiroTM

This PR adds the Role structure of `structures/Role.ts`.

2021-06-08 00:12 UTC, bsian03 requested changes
- Please call it GuildRole
- Permission should be bigint (or rather point to the Permissions enum)
- Interface names should be PascalCased

2021-06-08 00:13 UTC, bsian03 requested changes

2021-06-08 00:13 UTC, bsian03 commented on structures/Role.ts
> +  premium_subscriber: null;
```suggestion
  premium_subscriber?: null;
```

2021-06-09 22:37 UTC, bsian03 approved these changes

2021-06-12 21:51 UTC, Khaaz approved these changes

2021-06-12 21:51 UTC, merged