refactor(Structures): GuildMember
LibraryofCode/discordts pull request #38
Opened 2021-06-09 14:43 UTC by SiroTM

This PR makes the `premium_since` property optional.

2021-06-09 22:42 UTC, bsian03 requested changes

2021-06-09 22:42 UTC, bsian03 commented on structures/GuildMember.ts
>    permissions?: unknown; // TODO BigInt permissions;
Permissions are done, you may as well update them here now

2021-06-12 21:01 UTC, Khaaz approved these changes

2021-06-12 21:26 UTC, bsian03 approved these changes

2021-06-12 21:26 UTC, merged