refactor(Structures): Guild
LibraryofCode/discordts pull request #40
Opened 2021-06-09 14:50 UTC by SiroTM

This PR adds two properties:  `stage_instances` and `threads`. It also sets the type of `emojis`.

2021-06-09 22:48 UTC, bsian03 requested changes

2021-06-09 22:48 UTC, bsian03 commented on structures/Guild.ts
> +  stage_instances?: unknown[]; // TODO stage instance
Stage instance is done

2021-06-12 21:08 UTC, Khaaz approved these changes
lgtm

2021-06-12 21:09 UTC, Khaaz commented on structures/Guild.ts
> +  threads?: Channel[];
threads are regular channels?

2021-06-12 21:27 UTC, bsian03 commented on structures/Guild.ts
> +import Emoji from './Emoji';
```suggestion
import Emoji from './Emoji';
import GuildMember from './GuildMember';
```
OCD, sorry

2021-06-12 21:27 UTC, bsian03 approved these changes

2021-06-12 21:50 UTC, merged