feat(structures): Embed interface
LibraryofCode/discordts pull request #42
Opened 2021-06-12 03:55 UTC by matthew119427

Redo of https://github.com/libraryofcode/dis.ts/pull/24

2021-06-12 10:36 UTC, bsian03 requested changes

2021-06-12 10:36 UTC, bsian03 commented on structures/Embed.ts
> +export type EmbedType = 'rich' | 'image' | 'video' | 'gifv' | 'article' | 'link';
Enumerate this

2021-06-12 10:36 UTC, bsian03 commented on structures/Embed.ts
> +export default interface Embed {
This should be at the top

2021-08-11 16:08 UTC, matthew119427 commented on structures/Embed.ts
> +export default interface Embed {
Moved via commit 3cb89a2

2021-12-03 05:30 UTC, matthew119427 commented
no because that's exactly what i told her and she never fucking responded because she's a snake
and she and mckenzie know it by god

the next time i see that bitch it's on fuckin sight, hands will be thrown

2024-04-20 22:40 UTC, closed without merging